// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Key struct {
	ID        string
	Keyname   string
	Keycode   int64
	CreatedAt time.Time
}

type Mouse struct {
	ID        string
	Keyname   string
	IsMoved   int64
	IsScroll  int64
	Distance  int64
	Keycode   int64
	X         sql.NullInt64
	Y         sql.NullInt64
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
