// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Key struct {
	ID        int64
	Keyname   string
	Keycode   int64
	CreatedAt time.Time
}

type Mouse struct {
	ID        int64
	EventType string
	Button    string
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
