-- +goose Up
CREATE TABLE keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  keyname TEXT NOT NULL,
  keycode INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE keys;
