-- +goose Up
CREATE TABLE wmclass (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  wm_class TEXT NOT NULL,
  wm_name TEXT UNIQUE NOT NULL,
  start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  duration INTEGER NOT NULL,
  total_count INTEGER NOT NULL,
  is_active INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE wmclass;
